{{- if .Values.mountConfig }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "generic.fullname" . }}-config
data:
  {{- include "generic.config.configmap" (dict "context" $ "value" .Values.mountConfig ) | nindent 2 }}
{{- end }}
